name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake doxygen

      - name: Configure CMake
        working-directory: ${{ github.workspace }}
        run: cmake -B build

      - name: Build
        working-directory: ${{ github.workspace }}
        run: cmake --build build

      - name: Run tests
        working-directory: ${{ github.workspace }}
        run: ctest --test-dir build --output-on-failure

      - name: Generate docs
        if: ${{ success() }}
        working-directory: ${{ github.workspace }}
        run: cmake --build build --target doc_doxygen

      - name: Push generated docs to repository
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs
          git commit -m "Update Doxygen documentation"
          git push origin main
