name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake doxygen

      - name: Ensure build directory exists
        run: |
          if [ ! -d "build" ]; then
            mkdir build
          else
            echo "Build directory already exists"
          fi

      - name: Configure CMake and Build
        run: |
          cd build
          cmake ..
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Generate docs
        if: ${{ success() }}
        run: |
          cd build
          cmake --build . --target doc_doxygen

      - name: Push generated docs to repository
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs
          git commit -m "Update Doxygen documentation"
          git push origin main

